# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate summary of quality scores over position
#'
#' Description
#' @param inmat A matrix of score vectors per position
NULL

#' calculate Over Rep seqs
#'
#' @param infile  A string giving the path for the fastqfile
#' @param out_prefix A string giving the prefix to be used for outputs
#' @param buffer_size An int for the number of lines to keep in memory
#' @export
process_fastq <- function(infile, out_prefix, buffer_size) {
    invisible(.Call('_qckitfastq_process_fastq', PACKAGE = 'qckitfastq', infile, out_prefix, buffer_size))
}

qual_score_per_read <- function(infile) {
    .Call('_qckitfastq_qual_score_per_read', PACKAGE = 'qckitfastq', infile)
}

gc_per_read <- function(infile) {
    .Call('_qckitfastq_gc_per_read', PACKAGE = 'qckitfastq', infile)
}

calc_over_rep_seq <- function(infile, out_prefix, min_size = 5L, buffer_size = 1000000L) {
    .Call('_qckitfastq_calc_over_rep_seq', PACKAGE = 'qckitfastq', infile, out_prefix, min_size, buffer_size)
}

