# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get adapter content
#' @export
main <- function() {
    .Call('_qckitfastq_main', PACKAGE = 'qckitfastq')
}

#' calculate summary of quality scores over position
#'
#' Description
#' @param inmat A matrix of score vectors per position
NULL

#' calculate Over Rep seqs
#'
#' @param infile  A string giving the path for the fastqfile
#' @param buffer_size An int for the number of lines to keep in memory
#' @examples
#' infile <- system.file("extdata", "10^5_reads_test.fq.gz", package = "qckitfastq")
#' process_fastq(infile,10000)
#' @return process fastq and generate sequence and quality score tables
#' @export
process_fastq <- function(infile, buffer_size) {
    invisible(.Call('_qckitfastq_process_fastq', PACKAGE = 'qckitfastq', infile, buffer_size))
}

#' Calculate the mean quality score per read of the FASTQ gzipped file
#' 
#' @param infile A string giving the path for the fastqfile
#' @examples
#' infile <- system.file("extdata", "10^5_reads_test.fq.gz", package = "qckitfastq")
#' qual_score_per_read(infile)
#' @return mean quality per read
#' @export
qual_score_per_read <- function(infile) {
    .Call('_qckitfastq_qual_score_per_read', PACKAGE = 'qckitfastq', infile)
}

#' Calculate GC nucleotide sequence content per read of the FASTQ gzipped file
#' @param infile A string giving the path for the fastqfile
#' @examples
#' infile <- system.file("extdata", "10^5_reads_test.fq.gz", package = "qckitfastq")
#' gc_per_read(infile)[1:10]
#' @return GC content perncentage per read
#' @export
gc_per_read <- function(infile) {
    .Call('_qckitfastq_gc_per_read', PACKAGE = 'qckitfastq', infile)
}

#' Calculate sequece counts for each unique sequence and create a table with unique sequences
#' and corresponding counts
#' @param infile A string giving the path for the fastqfile
#' @param min_size An int for thhresholding over representation
#' @param buffer_size An int for the number of lines to keep in memory
#' @return calculate overrepresented sequence count
#' @export
calc_over_rep_seq <- function(infile, min_size = 5L, buffer_size = 1000000L) {
    .Call('_qckitfastq_calc_over_rep_seq', PACKAGE = 'qckitfastq', infile, min_size, buffer_size)
}

